apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.5.4
      pullPolicy: IfNotPresent
    replicaCount: 2